## Using Python to read data files and explore their contents

This notebook demonstrates using the [Pandas](http://pandas.pydata.org) data processing library to read a dataset into Python, and obtain a basic understanding of its contents.

Note that Python by itself is a general-purpose programming language and does not provide high-level data processing capabilities.  The Pandas library was developed to meet this need.  Pandas is the most popular Python library for data manipulation, and we will use it extensively in this course.

In addition to Pandas, we will also make use of the following Python libraries

* [Numpy](http://www.numpy.org) is a library for working with arrays of data

* [Matplotlib](https://matplotlib.org) is a library for making graphs

* [Seaborn](https://seaborn.pydata.org) is a higher-level interface to Matplotlib that can be used to simplify many graphing tasks

* [Statsmodels](https://www.statsmodels.org/stable/index.html) is a library that implements many statistical techniques

* [Scipy](https://www.scipy.org) is a library of techniques for numerical and scientific computing

### Importing libraries

When using Python, you must always begin your scripts by importing the libraries that you will be using. After importing a library, its functions can then be called from your code by prepending the library name to the function name.  For example, to use the '`dot`' function from the '`numpy`' library, you would enter '`numpy.dot`'.  To avoid repeatedly having to type the libary name in your scripts, it is conventional to define a two or three letter abbreviation for each library, e.g. '`numpy`' is usually abbreviated as '`np`'.  This allows us to use '`np.dot`' instead of '`numpy.dot`'.  Similarly, the Pandas library is typically abbreviated as '`pd`'.

The following statement imports the Pandas library, and gives it the abbreviated name 'pd'.

In [1]:
import pandas as pd

### Reading a data file

We will be working with the NHANES (National Health and Nutrition Examination Survey) data from the 2015-2016 wave, which has been discussed earlier in this course.  The raw data for this study are available here:

https://wwwn.cdc.gov/nchs/nhanes/Default.aspx

As in many large studies, the NHANES data are spread across multiple files.  The NHANES files are stored in [SAS transport](https://v8doc.sas.com/sashtml/files/z0987199.htm) (Xport) format.  This is a somewhat obscure format, and while Pandas is perfectly capable of reading the NHANES data directly from the xport files, accomplishing this task is a more advanced topic than we want to get into here.  Therefore, for this course we have prepared some merged datasets in text/csv format.

Pandas is a large and powerful library.  Here we will only use a few of its basic features.  The main data structure that Pandas works with is called a "data frame".  This is a two-dimensional table of data in which the rows typically represent cases (e.g. NHANES subjects), and the columns represent variables.  Pandas also has a one-dimensional data structure called a `Series` that we will encounter occasionally.

Pandas has a variety of functions named with the pattern '`read_xxx`' for reading data in different formats into Python.  Right now we will focus on reading '`csv`' files, so we are using the '`read_csv`' function, which can read csv (and "tsv") format files that are exported from spreadsheet software like Excel.  The '`read_csv`' function by default expects the first row of the data file to contain column names.  

Using '`read_csv`' in its default mode is fairly straightforward.  There are many options to '`read_csv`' that are useful for handling less-common situations.  For example, you would use the option `sep='\t'` instead of the default `sep=','` if the fields of your data file are delimited by tabs instead of commas.  See [here](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html) for the full documentation for '`read_csv`'.

Pandas can read a data file over the internet when provided with a URL, which is what we will do below.  In the Python script we will name the data set '`da`', i.e. this is the name of the Python variable that will hold the data frame after we have loaded it. 

The variable '`url`' holds a string (text) value, which is the internet URL where the data are located.  If you have the data file in your local filesystem, you can also use '`read_csv`' to read the data from this file.  In this case you would pass a file path instead of a URL, e.g. `pd.read_csv("my_file.csv")` would read a file named `my_file.csv` that is located in your current working directory.

In [2]:
url = "nhanes_2015_2016.csv"
da = pd.read_csv(url)
da

,SEQN,ALQ101,ALQ110,ALQ130,SMQ020,RIAGENDR,RIDAGEYR,RIDRETH1,DMDCITZN,DMDEDUC2,...,BPXSY2,BPXDI2,BMXWT,BMXHT,BMXBMI,BMXLEG,BMXARML,BMXARMC,BMXWAIST,HIQ210
0,83732,1.0,NaN,1.0,1,1,62,3,1.0,5.0,...,124.0,64.0,94.8,184.5,27.8,43.3,43.6,35.9,101.1,2.0
1,83733,1.0,NaN,6.0,1,1,53,3,2.0,3.0,...,140.0,88.0,90.4,171.4,30.8,38.0,40.0,33.2,107.9,NaN
2,83734,1.0,NaN,NaN,1,1,78,3,1.0,3.0,...,132.0,44.0,83.4,170.1,28.8,35.6,37.0,31.0,116.5,2.0
3,83735,2.0,1.0,1.0,2,2,56,3,1.0,5.0,...,134.0,68.0,109.8,160.9,42.4,38.5,37.7,38.3,110.1,2.0
4,83736,2.0,1.0,1.0,2,2,42,4,1.0,4.0,...,114.0,54.0,55.2,164.9,20.3,37.4,36.0,27.2,80.4,2.0
5,83737,2.0,2.0,NaN,2,2,72,1,2.0,2.0,...,122.0,58.0,64.4,150.0,28.6,34.4,33.5,31.4,92.9,NaN
6,83741,1.0,NaN,8.0,1,1,22,4,1.0,4.0,...,112.0,74.0,76.6,165.4,28.0,38.8,38.0,34.0,86.6,NaN
7,83742,1.0,NaN,1.0,2,2,32,1,2.0,4.0,...,114.0,70.0,64.5,151.3,28.2,34.1,33.1,31.5,93.3,2.0
8,83743,NaN,NaN,NaN,2,1,18,5,1.0,NaN,...,NaN,NaN,72.4,166.1,26.2,NaN,NaN,NaN,NaN,2.0
9,83744,1.0,NaN,NaN,2,1,56,4,1.0,3.0,...,180.0,114.0,108.3,179.4,33.6,46.0,44.1,38.5,116.0,2.0
10,83747,1.0,NaN,1.0,1,1,46,3,1.0,5.0,...,150.0,90.0,86.2,176.7,27.6,41.0,38.0,33.6,104.3,2.0
11,83750,1.0,NaN,3.0,1,1,45,5,1.0,2.0,...,108.0,72.0,76.2,177.8,24.1,43.9,37.8,33.0,90.1,NaN
12,83752,1.0,NaN,2.0,1,2,30,2,1.0,4.0,...,104.0,50.0,71.2,163.6,26.6,37.3,35.7,31.0,90.7,2.0
13,83754,2.0,1.0,1.0,2,2,67,2,1.0,5.0,...,116.0,64.0,117.8,164.1,43.7,34.8,38.6,42.7,123.0,2.0
14,83755,1.0,NaN,3.0,2,1,67,4,1.0,5.0,...,136.0,82.0,97.4,183.8,28.8,42.5,40.6,34.2,106.3,2.0
15,83757,1.0,NaN,1.0,2,2,57,2,1.0,1.0,...,146.0,62.0,80.5,150.8,35.4,31.6,32.7,33.7,113.5,2.0
16,83759,2.0,2.0,NaN,2,2,19,1,1.0,NaN,...,102.0,66.0,100.8,175.4,32.8,40.7,38.6,35.9,104.6,1.0
17,83761,1.0,NaN,1.0,2,2,24,5,2.0,5.0,...,108.0,60.0,61.8,156.4,25.3,37.0,35.5,29.6,79.5,NaN
18,83762,NaN,NaN,NaN,1,2,27,4,1.0,4.0,...,144.0,84.0,107.9,168.5,38.0,40.1,39.0,41.6,114.8,1.0
19,83767,2.0,2.0,NaN,2,2,54,5,1.0,4.0,...,126.0,82.0,59.0,149.9,26.3,32.7,33.3,30.4,88.9,2.0
20,83769,1.0,NaN,2.0,2,1,49,5,1.0,2.0,...,106.0,68.0,72.8,170.7,25.0,42.8,40.0,31.5,96.6,2.0
21,83773,2.0,2.0,NaN,2,2,80,3,1.0,3.0,...,146.0,68.0,67.7,149.8,30.2,33.4,36.2,30.3,108.4,2.0
22,83775,2.0,1.0,NaN,1,2,69,2,1.0,1.0,...,132.0,48.0,77.7,160.2,30.3,32.7,37.6,30.7,106.8,2.0
23,83776,NaN,NaN,NaN,2,2,58,1,1.0,5.0,...,110.0,62.0,56.6,157.5,22.8,34.5,31.0,28.0,83.0,2.0
24,83777,2.0,2.0,NaN,2,1,56,5,1.0,2.0,...,132.0,84.0,69.0,166.1,25.0,40.7,37.1,31.0,93.5,2.0
25,83781,1.0,NaN,3.0,2,2,27,4,1.0,5.0,...,110.0,66.0,87.8,160.7,34.0,41.4,33.7,32.1,103.6,2.0
26,83784,1.0,NaN,4.0,1,1,22,2,1.0,4.0,...,124.0,84.0,73.7,170.7,25.3,41.2,36.0,29.7,86.2,2.0
27,83785,2.0,1.0,1.0,1,2,60,2,1.0,5.0,...,136.0,74.0,75.6,145.2,35.9,31.0,33.1,36.0,108.0,2.0
28,83786,NaN,NaN,NaN,2,1,51,4,1.0,4.0,...,140.0,80.0,102.1,182.2,30.8,41.8,38.9,37.8,107.7,2.0
29,83787,2.0,2.0,NaN,2,2,68,1,1.0,1.0,...,124.0,58.0,77.4,152.0,33.5,33.4,34.6,34.9,103.1,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5705,93645,2.0,1.0,NaN,1,1,80,3,1.0,5.0,...,168.0,0.0,NaN,165.9,NaN,37.0,38.0,30.0,95.0,2.0
5706,93652,1.0,NaN,NaN,1,1,72,2,1.0,2.0,...,132.0,30.0,88.9,165.9,32.3,36.7,38.8,34.2,114.2,2.0
5707,93653,1.0,NaN,3.0,2,2,25,3,1.0,5.0,...,132.0,84.0,76.9,169.3,26.8,41.8,35.9,29.8,79.0,1.0
5708,93654,2.0,2.0,NaN,2,2,29,5,2.0,5.0,...,100.0,72.0,54.5,152.6,23.4,36.3,32.7,26.6,80.2,9.0
5709,93655,1.0,NaN,NaN,1,1,38,3,1.0,2.0,...,126.0,60.0,75.9,177.8,24.0,40.5,39.8,30.2,92.0,2.0
5710,93656,2.0,2.0,NaN,2,2,75,1,1.0,3.0,...,134.0,44.0,92.7,156.4,37.9,31.5,35.5,33.6,122.0,2.0
5711,93659,1.0,NaN,1.0,1,1,62,1,2.0,1.0,...,140.0,88.0,67.9,164.6,25.1,33.7,37.0,31.5,90.7,2.0
5712,93661,1.0,NaN,2.0,2,2,27,2,1.0,4.0,...,106.0,64.0,101.8,157.6,41.0,36.5,34.5,37.1,127.0,1.0
5713,93663,1.0,NaN,4.0,2,1,43,1,2.0,1.0,...,114.0,74.0,75.7,177.1,24.1,43.0,39.7,31.3,94.6,1.0
5714,93664,2.0,1.0,2.0,2,1,39,1,2.0,3.0,...,166.0,94.0,74.9,169.6,26.0,40.5,39.3,31.5,92.5,2.0
5715,93665,NaN,NaN,NaN,2,2,34,3,1.0,5.0,...,126.0,84.0,69.0,169.6,24.0,38.9,37.5,27.6,91.5,2.0
5716,93668,1.0,NaN,NaN,1,2,73,1,1.0,1.0,...,NaN,NaN,119.6,149.0,53.9,NaN,35.5,44.7,NaN,1.0
5717,93670,1.0,NaN,3.0,1,1,32,3,2.0,5.0,...,112.0,72.0,81.4,170.1,28.1,41.7,38.2,33.9,93.6,1.0
5718,93671,1.0,NaN,3.0,2,1,45,4,1.0,5.0,...,120.0,58.0,89.0,174.3,29.3,42.4,40.6,39.5,97.0,2.0
5719,93672,2.0,2.0,NaN,1,2,63,2,1.0,1.0,...,NaN,NaN,81.9,147.6,37.6,35.0,33.0,38.2,122.5,2.0
5720,93675,1.0,NaN,1.0,2,1,38,5,2.0,5.0,...,118.0,62.0,77.6,179.0,24.2,42.3,41.5,31.7,94.2,2.0
5721,93676,1.0,NaN,2.0,2,2,35,4,1.0,5.0,...,114.0,76.0,92.2,161.7,35.3,41.5,37.5,38.9,110.9,2.0
5722,93677,1.0,NaN,1.0,2,2,34,3,1.0,5.0,...,110.0,78.0,62.2,167.4,22.2,39.8,37.7,28.5,83.3,2.0
5723,93679,2.0,1.0,NaN,1,2,72,4,1.0,2.0,...,136.0,78.0,57.8,157.0,23.4,32.0,35.5,26.8,90.4,2.0
5724,93682,NaN,NaN,NaN,2,2,41,5,1.0,5.0,...,122.0,84.0,58.2,166.9,20.9,37.1,35.3,26.9,80.8,2.0
5725,93684,2.0,2.0,NaN,2,1,34,4,1.0,5.0,...,112.0,72.0,101.2,180.9,30.9,43.7,43.0,41.3,99.0,2.0
5726,93685,1.0,NaN,2.0,1,1,53,1,2.0,2.0,...,128.0,56.0,78.7,156.9,32.0,31.5,38.0,33.7,107.5,2.0
5727,93689,2.0,1.0,NaN,2,2,69,1,1.0,1.0,...,166.0,64.0,64.8,151.9,28.1,32.2,32.6,28.7,101.1,2.0
5728,93690,1.0,NaN,3.0,2,1,32,2,1.0,2.0,...,118.0,58.0,89.5,164.9,32.9,40.0,38.0,39.0,101.0,2.0
5729,93691,2.0,2.0,NaN,2,1,25,5,2.0,5.0,...,112.0,76.0,39.2,136.5,21.0,33.6,29.7,23.8,75.4,2.0
5730,93695,2.0,2.0,NaN,1,2,76,3,1.0,3.0,...,112.0,46.0,59.1,165.8,21.5,38.2,37.0,29.5,95.0,2.0
5731,93696,2.0,2.0,NaN,2,1,26,3,1.0,5.0,...,116.0,76.0,112.1,182.2,33.8,43.4,41.8,42.3,110.2,2.0
5732,93697,1.0,NaN,1.0,1,2,80,3,1.0,4.0,...,146.0,58.0,71.7,152.2,31.0,31.3,37.5,28.8,NaN,2.0
5733,93700,NaN,NaN,NaN,1,1,35,3,2.0,1.0,...,106.0,66.0,78.2,173.3,26.0,40.3,37.5,30.6,98.9,2.0
5734,93702,1.0,NaN,2.0,2,2,24,3,1.0,5.0,...,114.0,68.0,58.3,165.0,21.4,38.2,33.5,26.2,72.5,2.0

To confirm that we have actually obtained the data the we are expecting, we can display the shape (number of rows and columns) of the data frame in the notebook.  Note that the final expression in any Jupyter notebook cell is automatically printed, but you can force other expressions to be printed by using the '`print`' function, e.g. '`print(da.shape)`'.

Based on what we see below, the data set being read here has 5735 rows, corresponding to 5735 people in this wave of the NHANES study, and 28 columns, corresponding to 28 variables in this particular data file.  Note that NHANES collects thousands of variables on each study subject, but here we are working with a reduced file that contains a limited number of variables.

In [3]:
da.shape

(5735, 28)

### Exploring the contents of a data set

Pandas has a number of basic ways to understand what is in a data set.  For example, above we used the '`shape`' method to determine the numbers of rows and columns in a data set.  The columns in a Pandas data frame have names, to see the names, use the '`columns`' method:

In [4]:
da.columns

Index(['SEQN', 'ALQ101', 'ALQ110', 'ALQ130', 'SMQ020', 'RIAGENDR', 'RIDAGEYR',
       'RIDRETH1', 'DMDCITZN', 'DMDEDUC2', 'DMDMARTL', 'DMDHHSIZ', 'WTINT2YR',
       'SDMVPSU', 'SDMVSTRA', 'INDFMPIR', 'BPXSY1', 'BPXDI1', 'BPXSY2',
       'BPXDI2', 'BMXWT', 'BMXHT', 'BMXBMI', 'BMXLEG', 'BMXARML', 'BMXARMC',
       'BMXWAIST', 'HIQ210'],
      dtype='object')

These names correspond to variables in the NHANES study.  For example, `SEQN` is a unique identifier for one person, and `BMXWT` is the subject's weight in kilograms ("BMX" is the NHANES prefix for body measurements).  The variables in the NHANES data set are documented in a set of "codebooks" that are available on-line.  The codebooks for the 2015-2016 wave of NHANES can be found by following the links at the following page:

https://wwwn.cdc.gov/nchs/nhanes/continuousnhanes/default.aspx?BeginYear=2015

For convenience, direct links to some of the code books are included below:

* [Demographics code book](https://wwwn.cdc.gov/Nchs/Nhanes/2015-2016/DEMO_I.htm)

* [Body measures code book](https://wwwn.cdc.gov/Nchs/Nhanes/2015-2016/BMX_I.htm)

* [Blood pressure code book](https://wwwn.cdc.gov/Nchs/Nhanes/2015-2016/BPX_I.htm)

* [Alcohol questionaire code book](https://wwwn.cdc.gov/Nchs/Nhanes/2015-2016/ALQ_I.htm)

* [Smoking questionaire code book](https://wwwn.cdc.gov/Nchs/Nhanes/2015-2016/SMQ_I.htm)

Every variable in a Pandas data frame has a data type.  There are many different data types, but most commonly you will encounter floating point values (real numbers), integers, strings (text), and date/time values.  When Pandas reads a text/csv file, it guesses the data types based on what it sees in the first few rows of the data file.  Usually it selects an appropriate type, but occasionally it does not.  To confirm that the data types are consistent with what the variables represent, inspect the '`dtypes`' attribute of the data frame.

In [5]:
da.dtypes

SEQN          int64
ALQ101      float64
ALQ110      float64
ALQ130      float64
SMQ020        int64
RIAGENDR      int64
RIDAGEYR      int64
RIDRETH1      int64
DMDCITZN    float64
DMDEDUC2    float64
DMDMARTL    float64
DMDHHSIZ      int64
WTINT2YR    float64
SDMVPSU       int64
SDMVSTRA      int64
INDFMPIR    float64
BPXSY1      float64
BPXDI1      float64
BPXSY2      float64
BPXDI2      float64
BMXWT       float64
BMXHT       float64
BMXBMI      float64
BMXLEG      float64
BMXARML     float64
BMXARMC     float64
BMXWAIST    float64
HIQ210      float64
dtype: object

As we see here, most of the variables have floating point or integer data type.  Unlike many data sets, NHANES does not use any text values in its data.  For example, while many datasets would use text labels like "F" or "M" to denote a subject's gender, this information is represented in NHANES with integer codes.  The actual meanings of these codes can be determined from the codebooks.  For example, the variable `RIAGENDR` contains each subject's gender, with male gender coded as `1` and female gender coded as `2`.  The `RIAGENDR` variable is part of the demographics component of NHANES, so this coding can be found in the demographics codebook.

Variables like `BMXWT` which represent a quantitative measurement will typically be stored as floating point data values.

### Slicing a data set

As discussed above, a Pandas data frame is a rectangular data table, in which the rows represent cases and the columns represent variables.  One common manipulation of a data frame is to extract the data for one case or for one variable.  There are several ways to do this, as shown below.

To extract all the values for one variable, the following three approaches are equivalent ("DMDEDUC2" here is an NHANES variable containing a person's educational attainment).  In these four lines of code, we are assigning the data from one column of the data frame `da` into new variables `w`, `x`, `y`, and `z`.  The first three approaches access the variable by name.  The fourth approach accesses the variable by position (note that `DMDEDUC2` is in position 9 of the `da.columns` array shown above -- remember that Python counts starting at position zero).

In [6]:
w = da["DMDEDUC2"]
x = da.loc[:, "DMDEDUC2"]
y = da.DMDEDUC2
z = da.iloc[:, 9]  # DMDEDUC2 is in column 9

Another reason to slice a variable out of a data frame is so that we can then pass it into a function.  For example, we can find the maximum value over all `DMDEDUC2` values using any one of the following four lines of code:

In [7]:
print(da["DMDEDUC2"].max())
print(da.loc[:, "DMDEDUC2"].max())
print(da.DMDEDUC2.max())
print(da.iloc[:, 6].max())

9.0
9.0
9.0
80

Every value in a Python program has a type, and the type information can be obtained using Python's '`type`' function.  This can be useful, for example, if you are looking for the documentation associated with some value, but you do not know what the value's type is.  

Here we see that the variable `da` has type 'DataFrame', while one column of `da` has type 'Series'.  As noted above, a Series is a Pandas data structure for holding a single column (or row) of data.

In [8]:
print(type(da)) # The type of the variable
print(type(da.DMDEDUC2)) # The type of one column of the data frame
print(type(da.iloc[2,:])) # The type of one row of the data frame

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>

It may also be useful to slice a row (case) out of a data frame.  Just as a data frame's columns have names, the rows also have names, which are called the "index".  However many data sets do not have meaningful row names, so it is more common to extract a row of a data frame using its position.  The `iloc` method slices rows or columns from a data frame by position (counting from 0). The following line of code extracts row 3 from the data set (which is the fourth row, counting from zero).

In [9]:
x = da.iloc[3, :]
x

SEQN         83735.0
ALQ101           2.0
ALQ110           1.0
ALQ130           1.0
SMQ020           2.0
RIAGENDR         2.0
RIDAGEYR        56.0
RIDRETH1         3.0
DMDCITZN         1.0
DMDEDUC2         5.0
DMDMARTL         6.0
DMDHHSIZ         1.0
WTINT2YR    102718.0
SDMVPSU          1.0
SDMVSTRA       131.0
INDFMPIR         5.0
BPXSY1         132.0
BPXDI1          72.0
BPXSY2         134.0
BPXDI2          68.0
BMXWT          109.8
BMXHT          160.9
BMXBMI          42.4
BMXLEG          38.5
BMXARML         37.7
BMXARMC         38.3
BMXWAIST       110.1
HIQ210           2.0
Name: 3, dtype: float64

Another important data frame manipulation is to extract a contiguous block of rows or columns from the data set.  Below we slice by position, in the first case taking row positions 3 and 4 (counting from 0, which are rows 4 and 5 counting from 1), and in the second case taking columns 2, 3, and 4 (columns 3, 4, 5 if counting from 1).

In [10]:
#x = da.iloc[3:5, :]
y = da.iloc[:, 2:5]
#x
y

      ALQ110  ALQ130  SMQ020
0        NaN     1.0       1
1        NaN     6.0       1
2        NaN     NaN       1
3        1.0     1.0       2
4        1.0     1.0       2
5        2.0     NaN       2
6        NaN     8.0       1
7        NaN     1.0       2
8        NaN     NaN       2
9        NaN     NaN       2
10       NaN     1.0       1
11       NaN     3.0       1
12       NaN     2.0       1
13       1.0     1.0       2
14       NaN     3.0       2
15       NaN     1.0       2
16       2.0     NaN       2
17       NaN     1.0       2
18       NaN     NaN       1
19       2.0     NaN       2
20       NaN     2.0       2
21       2.0     NaN       2
22       1.0     NaN       1
23       NaN     NaN       2
24       2.0     NaN       2
25       NaN     3.0       2
26       NaN     4.0       1
27       1.0     1.0       1
28       NaN     NaN       2
29       2.0     NaN       2
...      ...     ...     ...
5705     1.0     NaN       1
5706     NaN     NaN       1
5707     NaN     3.0       2
5708     2.0     NaN       2
5709     NaN     NaN       1
5710     2.0     NaN       2
5711     NaN     1.0       1
5712     NaN     2.0       2
5713     NaN     4.0       2
5714     1.0     2.0       2
5715     NaN     NaN       2
5716     NaN     NaN       1
5717     NaN     3.0       1
5718     NaN     3.0       2
5719     2.0     NaN       1
5720     NaN     1.0       2
5721     NaN     2.0       2
5722     NaN     1.0       2
5723     1.0     NaN       1
5724     NaN     NaN       2
5725     2.0     NaN       2
5726     NaN     2.0       1
5727     1.0     NaN       2
5728     NaN     3.0       2
5729     2.0     NaN       2
5730     2.0     NaN       1
5731     2.0     NaN       2
5732     NaN     1.0       1
5733     NaN     NaN       1
5734     NaN     2.0       2

[5735 rows x 3 columns]

### Missing values

When reading a dataset using Pandas, there is a set of values including 'NA', 'NULL', and 'NaN' that are taken by default to represent a missing value.  The full list of default missing value codes is in the '`read_csv`' documentation [here](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html).  This document also explains how to change the way that '`read_csv`' decides whether a variable's value is missing.

Pandas has functions called `isnull` and `notnull` that can be used to identify where the missing and non-missing values are located in a data frame.  Below we use these functions to count the number of missing and non-missing `DMDEDUC2` values.

In [12]:
print(pd.isnull(da.DMDEDUC2).sum())
print(pd.notnull(da.DMDEDUC2).sum())

261
5474

As an aside, note that there may be a variety of distinct forms of missingness in a variable, and in some cases it is important to keep these values distinct.  For example, in case of the DMDEDUC2 variable, in addition to the blank or NA values that Pandas considers to be missing, three people responded "don't know" (code value 9).  In many analyses, the "don't know" values will also be treated as missing, but at this point we are considering "don't know" to be a distinct category of observed response.